# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  admin_name: Administrator
  admin_email: administrator@tdt4242.shop
  admin_password: administrator
  seller_name: Seller
  seller_email: seller@tdt4242.shop
  seller_password: seller
  customer_name: Customer
  customer_email: customer@tdt4242.shop
  customer_password: customer
  domain_name: tdt424.shop
  secret_key_base: c6af7b3b873e6c184d39d4be9b568ef963e8dd001f1020f75d1788f468705c4c7f3dc9241387048dff06331ad78ddf7ec757c49142dd619e4d304648feb6a335

test:
  domain_name: tdt4242.shop
  secret_key_base: f87256d8db9c36ca861f1c61c9e0e290e7b1d13fc774315f4b0a73bb1da09a55164de6879f7565293e3219249ba5706adb0a7d4d7acad65a05c7d6d67af1ee76

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  seller_name: Seller
  seller_email: seller@tdt4242.shop
  seller_password: seller
  customer_name: Customer
  customer_email: customer@tdt4242.shop
  customer_password: customer
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
